# In _config.yml
title: Higher Level Programming 2023
root: index
author: |
  Hans Petter Langtangen,
  Joakim Sundnes, Ola Skavhaug, Jonathan Feinberg, Karl-Erik Holter,
  Vidar Tonaas Fauske, Benjamin Ragan-Kelley, Lisa Pankewitz,
  Sebastian Mitusch, Simon Funke, Ingeborg Gjerde, Vegard Vinje,
  and Miroslav Kuchta

# disable execution to start
execute:
  execute_notebooks: "off"
only_build_toc_files: true
