# In _config.yml
title: Higher Level Programming 2023
root: index
author: |
  Hans Petter Langtangen,
  Joakim Sundnes, Ola Skavhaug, Jonathan Feinberg, Karl-Erik Holter,
  Vidar Tonaas Fauske, Benjamin Ragan-Kelley, Lisa Pankewitz,
  Sebastian Mitusch, Simon Funke, Ingeborg Gjerde, Vegard Vinje,
  and Miroslav Kuchta

# disable execution to start
execute:
  execute_notebooks: "off"
only_build_toc_files: true

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution
    - tasklist

sphinx:
  extra_extensions:
    - copy_files
  config:
    myst_substitutions:
      course: IN3110/IN4110
      semester: h23
      course_page: https://www.uio.no/studier/emner/matnat/ifi/IN3110/h23
      course_link: "[UiO course website](https://www.uio.no/studier/emner/matnat/ifi/IN3110/h23)"
    linkcheck_ignore:
      - https://mattermost.uio.no/.*
    suppress_warnings: ["mystnb.unknown_mime_type"]
    copy_files:
      - "lectures/**/figs"
  local_extensions:
    copy_files: sphinxext
