# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      # checkout the repository
      - uses: actions/checkout@v2

      # setup Python
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade -r dev-requirements.txt -r requirements.txt .
          pip freeze

      - name: Run tests
        run: |
          pytest -v --color=yes
