python_integration_tools.pdf: python_integration_tools.dot
	dot -Tpdf python_integration_tools.dot -o python_integration_tools.pdf
	dot -Tsvg python_integration_tools.dot -o python_integration_tools.svg
