language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -r requirements.txt
install:
  - pip install .
script: pytest
